import { Attribute } from "../attributes/attributes"

export enum Race {
    ELF = 'ELF',
    HUMAN = 'HUMAN',
    GOBLIN = 'GOBLIN',
    ORC = 'ORC',
    DWARF = 'DWARF',
    TROLL = 'TROLL',
}

export const RACE_BONUSES: {[race in Race]: {[attribute in Attribute]: number}} = {
    [Race.ELF]: {
        [Attribute.HEALTH]: 0.9,
        [Attribute.STRENGTH]: 0.9,
        [Attribute.ENDURANCE]: 1.5,
        [Attribute.AVOIDANCE]: 1.55,
        [Attribute.INITIATIVE]: 1.4,
        [Attribute.PIERCING]: 1.3,
        [Attribute.HAMMER]: 0.9,
        [Attribute.SWORD]: 1.15,
        [Attribute.AXE]: 1,
        [Attribute.FLAIL]: 0.9,
        [Attribute.STAFF]: 1.2,
        [Attribute.UNARMED]: 0.7,
        [Attribute.SHIELD]: 1.25,
    },

    [Race.HUMAN]: {
        [Attribute.HEALTH]: 1.1,
        [Attribute.STRENGTH]: 1.1,
        [Attribute.ENDURANCE]: 1.1,
        [Attribute.AVOIDANCE]: 1.1,
        [Attribute.INITIATIVE]: 1.1,
        [Attribute.PIERCING]: 1.15,
        [Attribute.HAMMER]: 1.1,
        [Attribute.SWORD]: 1.2,
        [Attribute.AXE]: 1.2,
        [Attribute.FLAIL]: 1.1,
        [Attribute.STAFF]: 1.1,
        [Attribute.UNARMED]: 1.1,
        [Attribute.SHIELD]: 1.15,
    },

    [Race.GOBLIN]: {
        [Attribute.HEALTH]: 0.85,
        [Attribute.STRENGTH]: 1.2,
        [Attribute.ENDURANCE]: 1,
        [Attribute.AVOIDANCE]: 1.3,
        [Attribute.INITIATIVE]: 1.1,
        [Attribute.PIERCING]: 1.3,
        [Attribute.HAMMER]: 1.3,
        [Attribute.SWORD]: 0.8,
        [Attribute.AXE]: 0.9,
        [Attribute.FLAIL]: 1.1,
        [Attribute.STAFF]: 0.9,
        [Attribute.UNARMED]: 1.2,
        [Attribute.SHIELD]: 0.95,
    },

    [Race.ORC]: {
        [Attribute.HEALTH]: 1.2,
        [Attribute.STRENGTH]: 1.3,
        [Attribute.ENDURANCE]: 0.9,
        [Attribute.AVOIDANCE]: 0.7,
        [Attribute.INITIATIVE]: 0.95,
        [Attribute.PIERCING]: 1.05,
        [Attribute.HAMMER]: 1.1,
        [Attribute.SWORD]: 1,
        [Attribute.AXE]: 1.1,
        [Attribute.FLAIL]: 1.1,
        [Attribute.STAFF]: 0.75,
        [Attribute.UNARMED]: 0.9,
        [Attribute.SHIELD]: 0.9,
    },

    [Race.DWARF]: {
        [Attribute.HEALTH]: 1.3,
        [Attribute.STRENGTH]: 1.2,
        [Attribute.ENDURANCE]: 0.8,
        [Attribute.AVOIDANCE]: 0.6,
        [Attribute.INITIATIVE]: 0.8,
        [Attribute.PIERCING]: 0.7,
        [Attribute.HAMMER]: 1.2,
        [Attribute.SWORD]: 1,
        [Attribute.AXE]: 1.2,
        [Attribute.FLAIL]: 1,
        [Attribute.STAFF]: 0.7,
        [Attribute.UNARMED]: 0.85,
        [Attribute.SHIELD]: 1.2,
    },

    [Race.TROLL]: {
        [Attribute.HEALTH]: 1.55,
        [Attribute.STRENGTH]: 1.45,
        [Attribute.ENDURANCE]: 0.6,
        [Attribute.AVOIDANCE]: 0.4,
        [Attribute.INITIATIVE]: 0.6,
        [Attribute.PIERCING]: 0.75,
        [Attribute.HAMMER]: 0.85,
        [Attribute.SWORD]: 0.7,
        [Attribute.AXE]: 0.8,
        [Attribute.FLAIL]: 0.85,
        [Attribute.STAFF]: 0.65,
        [Attribute.UNARMED]: 0.7,
        [Attribute.SHIELD]: 0.8,
    },
}