import { Attribute, WeaponSkill } from '../attributes/attributes'
import * as _ from 'lodash'

export enum Race {
  ELF = 'ELF',
  HUMAN = 'HUMAN',
  GOBLIN = 'GOBLIN',
  ORC = 'ORC',
  DWARF = 'DWARF',
  TROLL = 'TROLL',
  UNDEAD_ELF = 'UNDEAD_ELF',
  UNDEAD_HUMAN = 'UNDEAD_HUMAN',
  UNDEAD_GOBLIN = 'UNDEAD_GOBLIN',
  UNDEAD_ORC = 'UNDEAD_ORC',
  UNDEAD_DWARF = 'UNDEAD_DWARF',
  UNDEAD_TROLL = 'UNDEAD_TROLL',
}

export const RACE_LABELS: { [race in Race]: string } = {
  [Race.ELF]: 'Elf',
  [Race.HUMAN]: 'Human',
  [Race.GOBLIN]: 'Goblin',
  [Race.ORC]: 'Orc',
  [Race.DWARF]: 'Dwarf',
  [Race.TROLL]: 'Troll',
  [Race.UNDEAD_ELF]: 'Undead (Elf)',
  [Race.UNDEAD_HUMAN]: 'Undead (Human)',
  [Race.UNDEAD_GOBLIN]: 'Undead (Goblin)',
  [Race.UNDEAD_ORC]: 'Undead (Orc)',
  [Race.UNDEAD_DWARF]: 'Undead (Dwarf)',
  [Race.UNDEAD_TROLL]: 'Undead (Troll)',
}

const UNDEAD_RACE_MODIFIERS: { [attribute in Attribute | WeaponSkill]: number } = {
  [Attribute.STAMINA]: 1.1,
  [Attribute.STRENGTH]: 1,
  [Attribute.ENDURANCE]: 2,
  [Attribute.DODGE]: 1.05,
  [Attribute.INITIATIVE]: 0.9,
  [WeaponSkill.SPEAR]: 1.05,
  [WeaponSkill.MACE]: 1.05,
  [WeaponSkill.SWORD]: 1.05,
  [WeaponSkill.AXE]: 1.05,
  [WeaponSkill.CHAIN]: 1.05,
  [WeaponSkill.STAVE]: 1.05,
  [Attribute.SHIELD]: 1.05,
}

const UNDEAD_ESSENCE_MODIFIERS: { [race in Race]?: { [attribute in Attribute | WeaponSkill]: number } } = {
  [Race.ELF]: {
    [Attribute.STAMINA]: 0.95,
    [Attribute.STRENGTH]: 0.9,
    [Attribute.ENDURANCE]: 1,
    [Attribute.DODGE]: 1.2,
    [Attribute.INITIATIVE]: 1.1,
    [WeaponSkill.SPEAR]: 1,
    [WeaponSkill.MACE]: 1,
    [WeaponSkill.SWORD]: 1,
    [WeaponSkill.AXE]: 1,
    [WeaponSkill.CHAIN]: 1,
    [WeaponSkill.STAVE]: 1,
    [Attribute.SHIELD]: 1,
  },
  [Race.HUMAN]: {
    [Attribute.STAMINA]: 1,
    [Attribute.STRENGTH]: 1,
    [Attribute.ENDURANCE]: 1,
    [Attribute.DODGE]: 1,
    [Attribute.INITIATIVE]: 1,
    [WeaponSkill.SPEAR]: 1.1,
    [WeaponSkill.MACE]: 1.1,
    [WeaponSkill.SWORD]: 1.1,
    [WeaponSkill.AXE]: 1.1,
    [WeaponSkill.CHAIN]: 1.1,
    [WeaponSkill.STAVE]: 1.1,
    [Attribute.SHIELD]: 1.1,
  },
  [Race.GOBLIN]: {
    [Attribute.STAMINA]: 0.9,
    [Attribute.STRENGTH]: 1.1,
    [Attribute.ENDURANCE]: 1,
    [Attribute.DODGE]: 1.1,
    [Attribute.INITIATIVE]: 1,
    [WeaponSkill.SPEAR]: 1,
    [WeaponSkill.MACE]: 1,
    [WeaponSkill.SWORD]: 1,
    [WeaponSkill.AXE]: 1,
    [WeaponSkill.CHAIN]: 1,
    [WeaponSkill.STAVE]: 1,
    [Attribute.SHIELD]: 1,
  },
  [Race.ORC]: {
    [Attribute.STAMINA]: 1,
    [Attribute.STRENGTH]: 1.1,
    [Attribute.ENDURANCE]: 1,
    [Attribute.DODGE]: 0.8,
    [Attribute.INITIATIVE]: 1.1,
    [WeaponSkill.SPEAR]: 1,
    [WeaponSkill.MACE]: 1,
    [WeaponSkill.SWORD]: 1,
    [WeaponSkill.AXE]: 1,
    [WeaponSkill.CHAIN]: 1,
    [WeaponSkill.STAVE]: 1,
    [Attribute.SHIELD]: 1,
  },
  [Race.DWARF]: {
    [Attribute.STAMINA]: 1.1,
    [Attribute.STRENGTH]: 1.05,
    [Attribute.ENDURANCE]: 1,
    [Attribute.DODGE]: 0.8,
    [Attribute.INITIATIVE]: 1,
    [WeaponSkill.SPEAR]: 1,
    [WeaponSkill.MACE]: 1,
    [WeaponSkill.SWORD]: 1,
    [WeaponSkill.AXE]: 1,
    [WeaponSkill.CHAIN]: 1,
    [WeaponSkill.STAVE]: 1,
    [Attribute.SHIELD]: 1,
  },
  [Race.TROLL]: {
    [Attribute.STAMINA]: 1.2,
    [Attribute.STRENGTH]: 1.3,
    [Attribute.ENDURANCE]: 0.6,
    [Attribute.DODGE]: 0.4,
    [Attribute.INITIATIVE]: 0.6,
    [WeaponSkill.SPEAR]: 0.85,
    [WeaponSkill.MACE]: 0.9,
    [WeaponSkill.SWORD]: 0.8,
    [WeaponSkill.AXE]: 0.85,
    [WeaponSkill.CHAIN]: 0.9,
    [WeaponSkill.STAVE]: 0.8,
    [Attribute.SHIELD]: 0.85,
  },
}

const getUndeadModifiers = (race: Race): { [attribute in Attribute | WeaponSkill]: number } => {
  return {
    ..._.mapValues(
      Attribute,
      (attribute: Attribute) => UNDEAD_RACE_MODIFIERS[attribute] * UNDEAD_ESSENCE_MODIFIERS[race][attribute],
    ),
    ..._.mapValues(
      WeaponSkill,
      (weaponSkill: WeaponSkill) => UNDEAD_RACE_MODIFIERS[weaponSkill] * UNDEAD_ESSENCE_MODIFIERS[race][weaponSkill],
    ),
  }
}

export const RACE_MODIFIERS: { [race in Race]: { [attribute in Attribute | WeaponSkill]: number } } = {
  [Race.ELF]: {
    [Attribute.STAMINA]: 0.9,
    [Attribute.STRENGTH]: 0.9,
    [Attribute.ENDURANCE]: 1.3,
    [Attribute.DODGE]: 1.55,
    [Attribute.INITIATIVE]: 1.25,
    [WeaponSkill.SPEAR]: 1.3,
    [WeaponSkill.MACE]: 1,
    [WeaponSkill.SWORD]: 1.15,
    [WeaponSkill.AXE]: 1,
    [WeaponSkill.CHAIN]: 1,
    [WeaponSkill.STAVE]: 1.2,
    [Attribute.SHIELD]: 1.25,
  },

  [Race.HUMAN]: {
    [Attribute.STAMINA]: 1.1,
    [Attribute.STRENGTH]: 1.1,
    [Attribute.ENDURANCE]: 1.1,
    [Attribute.DODGE]: 1.1,
    [Attribute.INITIATIVE]: 1.1,
    [WeaponSkill.SPEAR]: 1.15,
    [WeaponSkill.MACE]: 1.1,
    [WeaponSkill.SWORD]: 1.2,
    [WeaponSkill.AXE]: 1.2,
    [WeaponSkill.CHAIN]: 1.1,
    [WeaponSkill.STAVE]: 1.1,
    [Attribute.SHIELD]: 1.2,
  },

  [Race.GOBLIN]: {
    [Attribute.STAMINA]: 0.85,
    [Attribute.STRENGTH]: 1.2,
    [Attribute.ENDURANCE]: 1,
    [Attribute.DODGE]: 1.3,
    [Attribute.INITIATIVE]: 1.1,
    [WeaponSkill.SPEAR]: 1.2,
    [WeaponSkill.MACE]: 1.2,
    [WeaponSkill.SWORD]: 0.9,
    [WeaponSkill.AXE]: 1,
    [WeaponSkill.CHAIN]: 1.1,
    [WeaponSkill.STAVE]: 1.15,
    [Attribute.SHIELD]: 1,
  },
  [Race.ORC]: {
    [Attribute.STAMINA]: 1.2,
    [Attribute.STRENGTH]: 1.3,
    [Attribute.ENDURANCE]: 0.9,
    [Attribute.DODGE]: 0.7,
    [Attribute.INITIATIVE]: 0.95,
    [WeaponSkill.SPEAR]: 0.95,
    [WeaponSkill.MACE]: 1.1,
    [WeaponSkill.SWORD]: 1,
    [WeaponSkill.AXE]: 1.1,
    [WeaponSkill.CHAIN]: 1.1,
    [WeaponSkill.STAVE]: 0.85,
    [Attribute.SHIELD]: 0.95,
  },
  [Race.DWARF]: {
    [Attribute.STAMINA]: 1.3,
    [Attribute.STRENGTH]: 1.2,
    [Attribute.ENDURANCE]: 0.9,
    [Attribute.DODGE]: 0.6,
    [Attribute.INITIATIVE]: 0.85,
    [WeaponSkill.SPEAR]: 0.9,
    [WeaponSkill.MACE]: 1.2,
    [WeaponSkill.SWORD]: 1,
    [WeaponSkill.AXE]: 1.2,
    [WeaponSkill.CHAIN]: 1,
    [WeaponSkill.STAVE]: 0.85,
    [Attribute.SHIELD]: 1.1,
  },

  [Race.TROLL]: {
    [Attribute.STAMINA]: 1.5,
    [Attribute.STRENGTH]: 1.5,
    [Attribute.ENDURANCE]: 0.8,
    [Attribute.DODGE]: 0.4,
    [Attribute.INITIATIVE]: 0.6,
    [WeaponSkill.SPEAR]: 0.75,
    [WeaponSkill.MACE]: 0.85,
    [WeaponSkill.SWORD]: 0.7,
    [WeaponSkill.AXE]: 0.8,
    [WeaponSkill.CHAIN]: 0.85,
    [WeaponSkill.STAVE]: 0.65,
    [Attribute.SHIELD]: 0.8,
  },

  [Race.UNDEAD_ELF]: getUndeadModifiers(Race.ELF),
  [Race.UNDEAD_HUMAN]: getUndeadModifiers(Race.HUMAN),
  [Race.UNDEAD_GOBLIN]: getUndeadModifiers(Race.GOBLIN),
  [Race.UNDEAD_ORC]: getUndeadModifiers(Race.ORC),
  [Race.UNDEAD_DWARF]: getUndeadModifiers(Race.DWARF),
  [Race.UNDEAD_TROLL]: getUndeadModifiers(Race.TROLL),
}
